jobs:
  build:
    docker:
      - image: cimg/node:16.19.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: GATSBY_CPU_COUNT=1 GATSBY_SKIP_ADDON_PAGES=true yarn build
      - run: yarn test
      - run: yarn chromatic --exit-zero-on-changes

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^release-[0-9]+-[0-9]+$/
